Run ansible to provision k3s-01

diff --git a/.github/workflows/k3s-deploy.yml b/.github/workflows/k3s-deploy.yml
--- a/.github/workflows/k3s-deploy.yml
+++ b/.github/workflows/k3s-deploy.yml
@@ -74,6 +74,19 @@ jobs:
 
       - name: Run the Ansible playbook
         run: |
-          ssh -o StrictHostKeyChecking=no ubuntu@${{ env.GIT_RUNNER_IP }} << 'EOF'
-          cd ansible && ansible-playbook -i inventory/hosts.ini site.yml
-          EOF
+            ssh -o StrictHostKeyChecking=no ubuntu@${{ env.GIT_RUNNER_IP }} << 'EOF'
+                set -e
+                # Check installation
+                which ansible-playbook || echo "ansible-playbook not found in PATH"
+                echo "PATH: $PATH"
+                echo "Running Ansible playbook..."
+                
+                # Run the playbook if ansible-playbook is found
+                if command -v ansible-playbook > /dev/null; then
+                    cd ansible && ansible-playbook -i inventory/hosts.ini site.yml
+                else
+                    echo "Ansible is not installed. Exiting..."
+                    exit 1
+                fi
+            EOF
+
